name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      working-directory: ./docker/build-ubuntu
      run: |
        docker build . --file Dockerfile --tag ghcr.io/filipeoliveiraa/asterisk-unimrcp:latest
        docker push ghcr.io/filipeoliveiraa/asterisk-unimrcp:latest
